spring:
  profiles:
    active:
    - mac

---
# mac
spring:
  profiles: mac
  datasource:
    url: jdbc:mysql://127.0.0.1/security?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  devtools:
    restart:
      enabled: true
      additional-paths: security-browser/src/main
server:
  port: 8080
#security:
#  basic:
#    enabled: false
imooc:
  security:
    browser:
      loginPage: /demo-signIn.html
security:
  user:
    name: abc
    password: 123
    role: admin

