server:
  port: 8080
cupSize: C
age: 18
content: "cupSize:${cupSize},age:${age}"

girl:
  cupSize: B
  age: 20
spring:
  devtools:
    restart:
#      热部署生效
      enabled: true
#      监听目录
      additional-paths: src/main/java
#  关闭缓存及时刷新
  freemarker:
    cache: true
#    静态页面目录
  thymeleaf:
    cache: false